apiVersion: apps/v1
kind: Deployment
metadata:
  name: financial-literacy-backend
  namespace: financial-literacy
  labels:
    app: financial-literacy-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: financial-literacy-backend
  template:
    metadata:
      labels:
        app: financial-literacy-backend
    spec:
      containers:
      - name: backend
        image: financial-literacy/backend:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: financial-literacy-config
        - secretRef:
            name: financial-literacy-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5 