apiVersion: apps/v1
kind: Deployment
metadata:
  name: financial-literacy-backend
  namespace: financial-literacy
  labels:
    app: financial-literacy-backend
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: financial-literacy-backend
  template:
    metadata:
      labels:
        app: financial-literacy-backend
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: backend
        image: ${REGISTRY}/${BACKEND_IMAGE_NAME}:${IMAGE_TAG}
        ports:
        - containerPort: 8000
          name: http
        envFrom:
        - configMapRef:
            name: financial-literacy-config
        - secretRef:
            name: financial-literacy-secrets
        env:
        - name: PROMETHEUS_MULTIPROC_DIR
          value: "/tmp/prometheus"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: prometheus-multiproc
          mountPath: /tmp/prometheus
      volumes:
      - name: prometheus-multiproc
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: financial-literacy-backend-service
  namespace: financial-literacy
  labels:
    app: financial-literacy-backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: financial-literacy-backend
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  type: ClusterIP